import { Injectable } from '@nestjs/common';
import { SupabaseClient } from '@supabase/supabase-js';
import { BaseSupabaseAuthGuard } from 'nestjs-supabase-js';
import { jwtDecode } from 'jwt-decode'; // Requires "esModuleInterop": true in tsconfig.json

@Injectable()
export class MyAuthGuard extends BaseSupabaseAuthGuard {
  constructor(supabaseClient: SupabaseClient) {
    super(supabaseClient);
  }

  protected extractTokenFromRequest(request: Request): string | undefined {
    const cookies = (request as any).cookies;
    const part0 =
      cookies['sb-ginjmrvsyfbvxccpdqhq-auth-token.0'] ||
      'base64-eyJhY2Nlc3NfdG9rZW4iOiJleUpoYkdjaU9pSklVekkxTmlJc0ltdHBaQ0k2SWtOaWR6WkJkbkV5ZUVkaFNUVjJlWFlpTENKMGVYQWlPaUpLVjFRaWZRLmV5SnBjM01pT2lKb2RIUndjem92TDJkcGJtcHRjblp6ZVdaaWRuaGpZM0JrY1doeExuTjFjR0ZpWVhObExtTnZMMkYxZEdndmRqRWlMQ0p6ZFdJaU9pSXlNREl3TlRWbU9DMWlaRGRoTFRRM1lXRXRZV05pTkMwM05qWXhaamhsTnpRME1UWWlMQ0poZFdRaU9pSmhkWFJvWlc1MGFXTmhkR1ZrSWl3aVpYaHdJam94TnpRd09ETTNOVFl3TENKcFlYUWlPakUzTkRBNE16TTVOakFzSW1WdFlXbHNJam9pWW1GeVpHbGhZVGd6TUVCbmJXRnBiQzVqYjIwaUxDSndhRzl1WlNJNklpSXNJbUZ3Y0Y5dFpYUmhaR0YwWVNJNmV5SndjbTkyYVdSbGNpSTZJbWR2YjJkc1pTSXNJbkJ5YjNacFpHVnljeUk2V3lKbmIyOW5iR1VpWFgwc0luVnpaWEpmYldWMFlXUmhkR0VpT25zaVlYWmhkR0Z5WDNWeWJDSTZJbWgwZEhCek9pOHZiR2d6TG1kdmIyZHNaWFZ6WlhKamIyNTBaVzUwTG1OdmJTOWhMMEZEWnpodlkweEJTVTlrVVU5alZ6VkRPVFk1VkhaUVFYRnllVEJ0Yld0Q1FVUmpOSHBoYTJSVFpIQmFUazlHZUZOYU4wdE1hVTA5Y3prMkxXTWlMQ0psYldGcGJDSTZJbUpoY21ScFlXRTRNekJBWjIxaGFXd3VZMjl0SWl3aVpXMWhhV3hmZG1WeWFXWnBaV1FpT25SeWRXVXNJbVoxYkd4ZmJtRnRaU0k2SWtKaGNtUnBZU0JCYTJKaGNta2lMQ0pwYzNNaU9pSm9kSFJ3Y3pvdkwyRmpZMjkxYm5SekxtZHZiMmRzWlM1amIyMGlMQ0p1WVcxbElqb2lRbUZ5WkdsaElFRnJZbUZ5YVNJc0luQm9iMjVsWDNabGNtbG1hV1ZrSWpwbVlXeHpaU3dpY0dsamRIVnlaU0k2SW1oMGRIQnpPaTh2YkdnekxtZHZiMmRzWlhWelpYSmpiMjUwWlc1MExtTnZiUzloTDBGRFp6aHZZMHhCU1U5a1VVOWpWelZET1RZNVZIWlFRWEZ5ZVRCdGJXdENRVVJqTkhwaGEyUlRaSEJhVGs5R2VGTmFOMHRNYVUwOWN6azJMV01pTENKd2NtOTJhV1JsY2w5cFpDSTZJakV3TkRJMk1UQTRNVFF6TXpJd05UZzBOalE1TUNJc0luTjFZaUk2SWpFd05ESTJNVEE0TVRRek16SXdOVGcwTmpRNU1DSjlMQ0p5YjJ4bElqb2lZWFYwYUdWdWRHbGpZWFJsWkNJc0ltRmhiQ0k2SW1GaGJERWlMQ0poYlhJaU9sdDdJbTFsZEdodlpDSTZJbTloZFhSb0lpd2lkR2x0WlhOMFlXMXdJam94TnpRd09ESTFPRE0yZlYwc0luTmxjM05wYjI1ZmFXUWlPaUk1TlRjNE1qYzNaUzAxTmpNeUxUUmxPVFl0T0RKak5TMHhOV0UwTVdKak5EazVNREFpTENKcGMxOWhibTl1ZVcxdmRYTWlPbVpoYkhObGZRLm41OHJTYVdiMEF6S1VDR1dyRm4wOVRSc3RKT1lVZnM2S0lWMWFnRlNUaTgiLCJ0b2tlbl90eXBlIjoiYmVhcmVyIiwiZXhwaXJlc19pbiI6MzYwMCwiZXhwaXJlc19hdCI6MTc0MDgzNzU2MCwicmVmcmVzaF90b2tlbiI6IkV5aFo3WlRLaHNBWGpNNDliX2FlWXciLCJ1c2VyIjp7ImlkIjoiMjAyMDU1ZjgtYmQ3YS00N2FhLWFjYjQtNzY2MWY4ZTc0NDE2IiwiYXVkIjoiYXV0aGVudGljYXRlZCIsInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiZW1haWwiOiJiYXJkaWFhODMwQGdtYWlsLmNvbSIsImVtYWlsX2NvbmZpcm1lZF9hdCI6IjIwMjUtMDEtMTRUMTU6NTg6MTIuMTIwMTg0WiIsInBob25lIjoiIiwiY29uZmlybWVkX2F0IjoiMjAyNS0wMS0xNFQxNTo1ODoxMi4xMjAxODRaIiwibGFzdF9zaWduX2luX2F0IjoiMjAyNS0wMy0wMVQxMDo0Mzo1Ni45ODY5NDFaIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZ29vZ2xlIiwicHJvdmlkZXJzIjpbImdvb2dsZSJdfSwidXNlcl9tZXRhZGF0YSI6eyJhdmF0YXJfdXJsIjoiaHR0cHM6Ly9saDMuZ29vZ2xldXNlcmNvbnRlbnQuY29tL2EvQUNnOG9jTEFJT2RRT2NXNUM5NjlUdlBBcXJ5MG1ta0JBRGM0emFrZFNkcFpOT0Z4U1o3S0xpTT1zOTYtYyIsImVtYWlsIjoiYmFyZGlhYTgzMEBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiZnVsbF9uYW1lIjoiQmFyZGlhIEFrYmFyaSIsImlzcyI6Imh0dHBzOi8vYWNjb3VudHMuZ29vZ2xlLmNvbSIsIm5hbWUiOiJCYXJkaWEgQWtiYXJpIiwicGhvbmVfdmVyaWZpZWQiOmZhbHNlLCJwaWN0dXJlIjoiaHR0cHM6Ly9saDMuZ29vZ2xldXNlcmNvbnRlbnQuY29tL2EvQUNnOG9jTEFJT2RRT2NXNUM5NjlUdlBBcXJ5MG1ta0JBRGM0emFrZFNkcFpOT0Z4U1o3S0xpTT1zOTYtYyIsInByb3ZpZGVyX2lkIjoiMTA0MjYxMDgxNDMzMjA1ODQ2NDkwIiwic3ViIjoiMTA0MjYxMDgxNDMzMjA1ODQ2NDkwIn0sImlkZW50aXRpZXMiOlt7ImlkZW50aXR5X2lkIjoiMDZjN2I4YWEtYjExMS00OTFjLTg5Y2MtMWNlYzNkMmZmMmM4IiwiaWQiOiIxMDQyNjEwODE0MzMyMDU4NDY0OTAiLCJ1c2VyX2lkIjoiMjAyMDU1ZjgtYmQ3YS00N2FhLWFjYjQtNzY2M';
    const part1 =
      cookies['sb-ginjmrvsyfbvxccpdqhq-auth-token.1'] ||
      'WY4ZTc0NDE2IiwiaWRlbnRpdHlfZGF0YSI6eyJhdmF0YXJfdXJsIjoiaHR0cHM6Ly9saDMuZ29vZ2xldXNlcmNvbnRlbnQuY29tL2EvQUNnOG9jTEFJT2RRT2NXNUM5NjlUdlBBcXJ5MG1ta0JBRGM0emFrZFNkcFpOT0Z4U1o3S0xpTT1zOTYtYyIsImVtYWlsIjoiYmFyZGlhYTgzMEBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiZnVsbF9uYW1lIjoiQmFyZGlhIEFrYmFyaSIsImlzcyI6Imh0dHBzOi8vYWNjb3VudHMuZ29vZ2xlLmNvbSIsIm5hbWUiOiJCYXJkaWEgQWtiYXJpIiwicGhvbmVfdmVyaWZpZWQiOmZhbHNlLCJwaWN0dXJlIjoiaHR0cHM6Ly9saDMuZ29vZ2xldXNlcmNvbnRlbnQuY29tL2EvQUNnOG9jTEFJT2RRT2NXNUM5NjlUdlBBcXJ5MG1ta0JBRGM0emFrZFNkcFpOT0Z4U1o3S0xpTT1zOTYtYyIsInByb3ZpZGVyX2lkIjoiMTA0MjYxMDgxNDMzMjA1ODQ2NDkwIiwic3ViIjoiMTA0MjYxMDgxNDMzMjA1ODQ2NDkwIn0sInByb3ZpZGVyIjoiZ29vZ2xlIiwibGFzdF9zaWduX2luX2F0IjoiMjAyNS0wMS0xNFQxNTo1ODoxMi4xMTQ3ODNaIiwiY3JlYXRlZF9hdCI6IjIwMjUtMDEtMTRUMTU6NTg6MTIuMTE0ODc5WiIsInVwZGF0ZWRfYXQiOiIyMDI1LTAzLTAxVDEwOjQzOjUzLjQ3NzQ4NFoiLCJlbWFpbCI6ImJhcmRpYWE4MzBAZ21haWwuY29tIn1dLCJjcmVhdGVkX2F0IjoiMjAyNS0wMS0xNFQxNTo1ODoxMi4xMDk5MloiLCJ1cGRhdGVkX2F0IjoiMjAyNS0wMy0wMVQxMjo1ODo1OC42NTk5MThaIiwiaXNfYW5vbnltb3VzIjpmYWxzZX19';

    if (!part0 || !part1) {
      return undefined;
    }

    const combined = part0 + part1;

    const token = combined.startsWith('base64-') ? combined.slice(7) : combined;

    const decoded: any = jwtDecode(token, { header: true });

    this.supabaseClient.auth.setSession({
      access_token: decoded.access_token,
      refresh_token: decoded.refresh_token,
    });

    return decoded.access_token;
  }
}
